# Generated by Django 3.2.25 on 2025-04-08 09:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0002_delete_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_sensitivity', models.FloatField(default=0.5)),
                ('enable_sound', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='en', max_length=50)),
                ('camera_device', models.CharField(default='0', max_length=100)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_detections', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('most_common_gesture', models.CharField(blank=True, max_length=100)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('session_duration', models.DurationField(default=datetime.timedelta(0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesture', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='detection_clips/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
